# Change these first
owner: Jelly-Party # Your GitHub username
repo: jelly-party-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Jelly Party Website
    url: https://www.jelly-party.com/
  - name: Jelly Party Server
    check: "tcp-ping"
    url: ws.jelly-party.com
    port: 8080

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.jelly-party.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jelly Party Status
  introTitle: "Status Page for the Watch Party Browser Extension Jelly Party."
  introMessage: "The status of the Jelly Party Server is shown here."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
